# Generated by Django 2.2.7 on 2019-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survived', models.IntegerField(blank=True, null=True)),
                ('p_class', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('sip_sp', models.IntegerField(blank=True, null=True)),
                ('parch', models.IntegerField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('cabin', models.CharField(blank=True, max_length=100, null=True)),
                ('embarked', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
