# Generated by Django 2.2.7 on 2019-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={},
        ),
        migrations.AlterField(
            model_name='train',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
